In [1]:
import pandas as pd
import numpy as np
# 경고문구 무시
import warnings
warnings.filterwarnings('ignore')

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

# 이미지 해상도 높이기 
%config InlineBackend.figure_format = 'retina'
#한글
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

In [24]:
import urllib.request 
import json 
import pandas as pd 

url = 'https://bigdata.gwangju.go.kr/gjAPI/getGpBusiness/getGpBusinesslist.rd?apiSrvCd=0033&pageNo=1&numOfRow=1000'
# 데이터 가져오기
response = urllib.request.urlopen(url) 
json_str = response.read().decode('utf-8')

# JSON으로 변환
json_object = json.loads(json_str)


# 데이터프레임으로 변환
# data = pd.json_normalize(json_object['body']['items'])
data = pd.json_normalize(json_object['response']['body']['items'])

# 확인
data

,company_type,menu_1,price_1,phone,num,company_cap,company_nm,c_year,sigungu_nm,st_add
0,한식,설렁탕,"5,000원",222-0517,1156,김경녕,명덕식당,2016,동구,광주 동구 중앙로196번길 17(궁동)
1,이미용업,컷트,"5,000원",223-8119,1157,구창운,문화이용원,2016,동구,광주 동구 문화전당로23번길 36-4(금동)
2,한식,김치찌개,4000원,234-2002,1158,신창협,수라상,2016,동구,광주 동구 제봉로82번길 13-9(서석동)
3,한식,돼지갈비(250g),9000,224-6519,1159,최정기,화롯불,2016,동구,광주 동구 백서로 168(서석동)
4,중식,자장면,4000,227-0391,1160,윤영춘,삼미식당,2016,동구,광주 동구 백서로 189번길 14-32(서석동)
...,...,...,...,...,...,...,...,...,...,...
995,외식업,추어탕,"7,000",364-6182,2151,심경열,청송회관,2020,서구,광천1길 6-13(광천동)
996,외식업,백반,"6,000",364-2746,2152,박경자,무등회관,2020,서구,죽봉대로 111번길12(광천동)
997,외식업,추어탕,"6,000",352-8255,2153,김양현,상해회관,2020,서구,경열로 151-1(양동)
998,세탁업,정장드라이,"6,000",368-3931,2154,남기래,남진컴퓨터,2020,서구,구성로 109-3(양동)
999,이미용업,커트,"9,000",366-3436,2155,이유심,뉴욕진헤어,2020,서구,경열로 71(농성동)

In [25]:
data['price_1'] = data['price_1'].str.replace('원','')
data['price_1'] = data['price_1'].str.replace(',','')
data['price_1'] = data['price_1'].str.strip()

In [27]:
data = data.loc[(data['price_1'] !='4000\n(홀 3000)')]
data['price_1'].loc[(data['price_1'] =='')] = 0

In [28]:
data['price_1'] = data['price_1'].astype(int)

In [30]:
data.head()

,company_type,menu_1,price_1,phone,num,company_cap,company_nm,c_year,sigungu_nm,st_add
0,한식,설렁탕,5000,222-0517,1156,김경녕,명덕식당,2016,동구,광주 동구 중앙로196번길 17(궁동)
1,이미용업,컷트,5000,223-8119,1157,구창운,문화이용원,2016,동구,광주 동구 문화전당로23번길 36-4(금동)
2,한식,김치찌개,4000,234-2002,1158,신창협,수라상,2016,동구,광주 동구 제봉로82번길 13-9(서석동)
3,한식,돼지갈비(250g),9000,224-6519,1159,최정기,화롯불,2016,동구,광주 동구 백서로 168(서석동)
4,중식,자장면,4000,227-0391,1160,윤영춘,삼미식당,2016,동구,광주 동구 백서로 189번길 14-32(서석동)

In [31]:
data.loc[data['price_1']>=5000].sort_values(by='price_1',ascending=True).head(5)

,company_type,menu_1,price_1,phone,num,company_cap,company_nm,c_year,sigungu_nm,st_add
0,한식,설렁탕,5000,222-0517,1156,김경녕,명덕식당,2016,동구,광주 동구 중앙로196번길 17(궁동)
305,한식_일반,김치찌개,5000,062-234-2002,1461,신창협,수라상,2017,동구,광주광역시 동구 제봉로 82번길 13-9 (서석동)
308,한식_일반,김치찌개,5000,062-233-6288,1464,임우순,장터,2017,동구,광주광역시 동구 백서로 180-1 (서석동)
833,한식,김치찌개,5000,673-3466,1989,민영자,장미유황오리,2019,남구,대남대로181번길 23
311,한식_찌개류,설렁탕,5000,062-222-0517,1467,김경녕,명덕식당,2017,동구,광주광역시 동구 중앙로196번길 17 (궁동)

In [33]:
# xml 데이터 불러오기
# !pip install xml_to_dict
import requests
import pandas as pd
from xml_to_dict import XMLtoDict

url = 'http://apis.data.go.kr/6290000/tstreet/getTstreetList'
params ={'serviceKey' : 'FVPRuTOdKogjb9Q4m45eWqQeSIH6bbX6ngzvw3V/+Q/wqFKnrK0frU4eQj0BfxTwGkRZNHyQhi0lKxnREMolsA==', 
         'pageSize' : '1000', 
         'startPage' : '1' }

# 데이터 가져오기
response = requests.get(url, params=params)

# 딕셔너리로 변환
xd = XMLtoDict()
xd.parse(response.content)

# 데이터프레임으로 변환
data = pd.DataFrame(xd.parse(response.content)['response']['body']['data']['list'])

data.head()

,addr,addrRoad,area,association,baseDate,bicycle,bus,cart,cctv,city,...,parking,parkingNum,phone,registForm,storeNum,streetId,streetNm,streetType,subway,toilet
0,광주 북구 신안사거리~임동오거리,광주 북구 신안사거리~임동오거리,"14,353,6m2",Y,2021-11-04,N,Y,N,Y,광주광역시,...,Y,70,062-526-0770,10,150,1,자동차의거리,상설장,N,N
1,광주광역시 북구 용봉동 설죽로,광주광역시 북구 용봉동 설죽로,"75,598m2",Y,2021-11-04,N,Y,N,Y,광주광역시,...,N,0,062-511-7272,10,68,2,용봉동패션의거리,상설장,N,N
2,광주 북구 운암동 하남대로,광주 북구 운암동 하남대로,"82,725m2",Y,2021-11-04,N,Y,N,Y,광주광역시,...,Y,100,062-512-7191,10,174,3,공구의거리,상설장,N,N
3,광주광역시 동구 필문대로287번길 3,광주광역시 동구 필문대로287번길 3,"68,301,7m2",Y,2021-11-04,N,Y,N,Y,광주광역시,...,N,0,010-3608-2582,10,267,4,조대장미의거리,상설장,N,N
4,광주광역시 동구 금남로 167,광주광역시 동구 금남로 167,"22,878,6m2",Y,2021-11-04,N,Y,N,Y,광주광역시,...,Y,68,0507-1455-3011,10,143,5,전자의거리,상설장,Y,N

In [34]:
data.shape

(10, 36)

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 36 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   addr            10 non-null     object
 1   addrRoad        10 non-null     object
 2   area            10 non-null     object
 3   association     10 non-null     object
 4   baseDate        10 non-null     object
 5   bicycle         10 non-null     object
 6   bus             10 non-null     object
 7   cart            10 non-null     object
 8   cctv            10 non-null     object
 9   city            10 non-null     object
 10  county          10 non-null     object
 11  customerCenter  10 non-null     object
 12  deliveryApp     10 non-null     object
 13  disabledToilet  10 non-null     object
 14  establishYear   0 non-null      object
 15  fireExt         10 non-null     object
 16  fireplug        10 non-null     object
 17  giftCard        10 non-null     object
 18  homepage        3 non-null      object
 19  item            10 non-null     object
 20  latitude        10 non-null     object
 21  locker          10 non-null     object
 22  longitude       10 non-null     object
 23  lounge          10 non-null     object
 24  mainProduct     10 non-null     object
 25  openCycle       10 non-null     object
 26  parking         10 non-null     object
 27  parkingNum      10 non-null     object
 28  phone           6 non-null      object
 29  registForm      10 non-null     object
 30  storeNum        10 non-null     object
 31  streetId        10 non-null     object
 32  streetNm        10 non-null     object
 33  streetType      10 non-null     object
 34  subway          10 non-null     object
 35  toilet          10 non-null     object
dtypes: object(36)
memory usage: 2.9+ KB

In [36]:
data.isna().sum()

addr               0
addrRoad           0
area               0
association        0
baseDate           0
bicycle            0
bus                0
cart               0
cctv               0
city               0
county             0
customerCenter     0
deliveryApp        0
disabledToilet     0
establishYear     10
fireExt            0
fireplug           0
giftCard           0
homepage           7
item               0
latitude           0
locker             0
longitude          0
lounge             0
mainProduct        0
openCycle          0
parking            0
parkingNum         0
phone              4
registForm         0
storeNum           0
streetId           0
streetNm           0
streetType         0
subway             0
toilet             0
dtype: int64

In [37]:
data.columns

Index(['addr', 'addrRoad', 'area', 'association', 'baseDate', 'bicycle', 'bus',
       'cart', 'cctv', 'city', 'county', 'customerCenter', 'deliveryApp',
       'disabledToilet', 'establishYear', 'fireExt', 'fireplug', 'giftCard',
       'homepage', 'item', 'latitude', 'locker', 'longitude', 'lounge',
       'mainProduct', 'openCycle', 'parking', 'parkingNum', 'phone',
       'registForm', 'storeNum', 'streetId', 'streetNm', 'streetType',
       'subway', 'toilet'],
      dtype='object')

In [13]:
url = 'https://e-childschoolinfo.moe.go.kr/api/notice/excelDownload/basicInfo2.do'
df = pd.read_xml(url, xpath = './/list')

HTTPError: HTTP Error 400: Bad Request

In [38]:
# 유치원 기본현황 정보 조회    
    
import urllib.request 
import json 
import pandas as pd 

url = 'https://e-childschoolinfo.moe.go.kr/api/notice/basicInfo2.do?key=c31586baa15942d2a5ce66dcd22401d9&sidoCode=11&sggCode=11110'
# 데이터 가져오기
response = urllib.request.urlopen(url) 
json_str = response.read().decode('utf-8')

# JSON으로 변환
json_object = json.loads(json_str)


# 데이터프레임으로 변환
# data = pd.json_normalize(json_object['body']['items'])
# data = pd.json_normalize(json_object['response']['body']['items'])
data = pd.json_normalize(json_object['kinderInfo'])

# 확인
print(data.shape)
data.head()

(17, 31)

,key,kindercode,officeedu,subofficeedu,kindername,establish,edate,odate,addr,telno,...,shppcnt,rppnname,ldgrname,pbnttmng,prmstfcnt,ag3fpcnt,ag4fpcnt,ag5fpcnt,mixfpcnt,spcnfpcnt
0,1,1ecec08c-f026-b044-e053-0a32095ab044,서울특별시교육청,중부교육지원청,옥인유치원,사립(사인),19930430,19930430,서울특별시 종로구 자하문로 69,02-735-3984,...,None,이은호,이원경,20222,90,16,24,27,0,None
1,2,1ecec08c-f490-b044-e053-0a32095ab044,서울특별시교육청,중부교육지원청,한아름유치원,사립(사인),19930113,19930113,서울특별시 종로구 혜화로6가길 34,02-747-2449,...,None,정명호,김수진,20222,68,None,None,None,34,None
2,3,1ecec08c-f550-b044-e053-0a32095ab044,서울특별시교육청,중부교육지원청,서울혜화초등학교병설유치원,공립(병설),20030301,20030301,서울특별시 종로구 혜화로 32,02-763-0124,...,None,유재정,유재정,20222,46,None,22,24,0,None
3,4,1ecec08c-f736-b044-e053-0a32095ab044,서울특별시교육청,중부교육지원청,배화여자대학교 부속 배화유치원,사립(법인),19170401,19170401,서울특별시 종로구 필운대로1길 34,02-737-1433,...,None,학교법인 배화학원,이예숙,20222,110,22,26,30,0,None
4,5,1ecec08c-f910-b044-e053-0a32095ab044,서울특별시교육청,중부교육지원청,상명사대부속유치원,사립(법인),19660228,19660228,서울특별시 종로구 홍지문2길 1,02-396-1602,...,None,학교법인 상명학원,전승준,20222,150,43,52,55,0,None

In [39]:
# xml 데이터 불러오기
# !pip install xml_to_dict
import requests
import pandas as pd
from xml_to_dict import XMLtoDict

url = 'http://apis.data.go.kr/1611000/BldEngyService/getBeElctyUsgInfo'
params ={'serviceKey' : 'FVPRuTOdKogjb9Q4m45eWqQeSIH6bbX6ngzvw3V/+Q/wqFKnrK0frU4eQj0BfxTwGkRZNHyQhi0lKxnREMolsA==', 
         'sigunguCd' : '11680', 
         'bjdongCd' : '10300',
         'bun': '0012',
         'ji': '0000',
         'useYm': '201511'}

# 데이터 가져오기
response = requests.get(url, params=params)

# 딕셔너리로 변환
xd = XMLtoDict()
xd.parse(response.content)

# 데이터프레임으로 변환
data = pd.DataFrame(xd.parse(response.content)['response']['body']['items'])

data

                            item
bjdongCd                   10300
bun                         0012
ji                          0000
naMainBun                   21.0
naRoadCd            116804166040
naSubBun                     0.0
naUgrndCd                      0
newPlatPlc  서울특별시 강남구 개포로109길 21
platGbCd                       0
platPlc       서울특별시 강남구 개포동 12번지
rnum                           1
sigunguCd                  11680
useQty                 1042480.0
useYm                     201511

In [6]:
# 서울특별시_부동산 실거래가 정보
import urllib.request 
import json 
import pandas as pd 

url = 'http://openapi.seoul.go.kr:8088/784c6e4578736a75373242704f486a/json/tbLnOpendataRtmsV/1/1000/'

# 데이터 가져오기
response = urllib.request.urlopen(url) 
json_str = response.read().decode('utf-8')

# JSON으로 변환
json_object = json.loads(json_str)
json_object

# 데이터프레임으로 변환
# data = pd.json_normalize(json_object['body']['items'])
# data = pd.json_normalize(json_object['response']['body']['items'])
# data = pd.json_normalize(json_object['kinderInfo'])
data = pd.json_normalize(json_object['tbLnOpendataRtmsV']['row'])

# 확인
print(data.shape)
data.head()

(1000, 21)

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2022,11500,강서구,10500,마곡동,1,대지,0776,0004,엠코지니어스타,...,18000,23.84,33.39,5.0,,,2015,오피스텔,중개거래,서울 강서구
1,2022,11200,성동구,10900,금호동1가,1,대지,0001,0166,(1-166),...,24500,46.89,20.06,3.0,,,1999,연립다세대,중개거래,서울 성동구
2,2022,11710,송파구,10800,문정동,1,대지,0620,0000,송파푸르지오시티,...,25000,30.00,39.11,8.0,,,2013,오피스텔,직거래,
3,2022,11470,양천구,10300,신월동,1,대지,0482,0020,창우AEGISⅡ,...,21400,29.99,19.02,6.0,,,2016,연립다세대,중개거래,서울 강서구
4,2022,11500,강서구,10900,방화동,1,대지,0647,0020,신라힐,...,22700,57.36,0.00,8.0,,,2001,아파트,직거래,

In [3]:
import urllib.request 
import json 
import pandas as pd 

url = 'https://bigdata.kepco.co.kr/openapi/v1/powerUsage/houseAve.do?year=2020&month=11&metroCd=11&apiKey=TKnope8i7IhU8lq8sRjubhyK451C4Kfmhwm5fg1V&returnType=json'

# 데이터 가져오기
response = urllib.request.urlopen(url) 
json_str = response.read().decode('utf-8')

# JSON으로 변환
json_object = json.loads(json_str)
json_object

# 데이터프레임으로 변환
# data = pd.json_normalize(json_object['body']['items'])
# data = pd.json_normalize(json_object['response']['body']['items'])
# data = pd.json_normalize(json_object['kinderInfo'])
data = pd.json_normalize(json_object['data'])

# 확인
print(data.shape)
data.head()

(25, 7)

   year month  metro city  houseCnt  powerUsage   bill
0  2020    11  서울특별시  성동구    140446      231.08  24202
1  2020    11  서울특별시  도봉구    147436      230.37  23216
2  2020    11  서울특별시  은평구    224144      221.26  23811
3  2020    11  서울특별시  송파구    283474      246.04  27330
4  2020    11  서울특별시  양천구    190639      241.65  25897

In [7]:
    
    
import urllib.request 
import json 
import pandas as pd 

url = 'http://apis.data.go.kr/B552895/openapi/service/OrgPriceAuctionService/getRealMarketPriceList?ServiceKey=1yKMdSI9jST3NHMAjnb2FYpI4Gr+4FeldyFD8s1YlhoUHm3wywyvOp83ZtQLTh77IPD4F9O7WCcCfU0fkISOMg==&pageNo=1&numOfRows=10&delngDe=20151202&whsalCd=210005'
# 데이터 가져오기
response = urllib.request.urlopen(url) 
json_str = response.read().decode('utf-8')

# JSON으로 변환
json_object = json.loads(json_str)
json_object

# 데이터프레임으로 변환
# data = pd.json_normalize(json_object['body']['items'])
# data = pd.json_normalize(json_object['response']['body']['items'])
# data = pd.json_normalize(json_object['kinderInfo'])
# data = pd.json_normalize(json_object['data'])

# # 확인
# print(data.shape)
# data.head()

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [16]:
# xml 데이터 불러오기
# !pip install xml_to_dict
import requests
import pandas as pd
from xml_to_dict import XMLtoDict

url = 'http://apis.data.go.kr/B552895/openapi/service/OrgPriceAuctionService/getExactProdPriceList?ServiceKey=FVPRuTOdKogjb9Q4m45eWqQeSIH6bbX6ngzvw3V%2F%2BQ%2FwqFKnrK0frU4eQj0BfxTwGkRZNHyQhi0lKxnREMolsA%3D%3D&pageNo=1&numOfRows=10&delngDe=20151202&prdlstCd=1001'
params ={}

# 데이터 가져오기
response = requests.get(url, params=params)

# 딕셔너리로 변환
xd = XMLtoDict()
xd.parse(response.content)

# 데이터프레임으로 변환
data = pd.DataFrame(xd.parse(response.content)['response']['body']['items']['item'])

data

,aucSeCode,aucSeNm,catgoryCode,catgoryNewCode,catgoryNewNm,catgoryNm,cprInsttCode,cprInsttNewCode,cprMtcCode,cprMtcNm,...,stdSpciesCode,stdSpciesNewCode,stdSpciesNewNm,stdSpciesNm,stdUnitNewCode,stdUnitNewNm,whsalMrktCode,whsalMrktNewCode,whsalMrktNewNm,whsalMrktNm
0,2,정가수의,10,10,엽경채류,엽경채류,22000111,6041404,536000,전라남도 해남군,...,100101,100101,봄배추,봄배추,12,kg,220001,1041401,대구북부도매시장,대구북부도매시장
1,2,정가수의,10,10,엽경채류,엽경채류,22000111,6041404,536000,전라남도 해남군,...,100101,100101,봄배추,봄배추,12,kg,220001,1041401,대구북부도매시장,대구북부도매시장
2,2,정가수의,10,10,엽경채류,엽경채류,22000111,6041404,536000,전라남도 해남군,...,100101,100101,봄배추,봄배추,12,kg,220001,1041401,대구북부도매시장,대구북부도매시장
3,2,정가수의,10,10,엽경채류,엽경채류,22000111,6041404,536000,전라남도 해남군,...,100101,100101,봄배추,봄배추,12,kg,220001,1041401,대구북부도매시장,대구북부도매시장
4,2,정가수의,10,10,엽경채류,엽경채류,22000111,6041404,536000,전라남도 해남군,...,100101,100101,봄배추,봄배추,12,kg,220001,1041401,대구북부도매시장,대구북부도매시장
5,2,정가수의,10,10,엽경채류,엽경채류,22000111,6041404,536000,전라남도 해남군,...,100101,100101,봄배추,봄배추,12,kg,220001,1041401,대구북부도매시장,대구북부도매시장
6,2,정가수의,10,10,엽경채류,엽경채류,22000111,6041404,536000,전라남도 해남군,...,100101,100101,봄배추,봄배추,12,kg,220001,1041401,대구북부도매시장,대구북부도매시장
7,2,정가수의,10,10,엽경채류,엽경채류,22000111,6041404,536000,전라남도 해남군,...,100101,100101,봄배추,봄배추,12,kg,220001,1041401,대구북부도매시장,대구북부도매시장
8,2,정가수의,10,10,엽경채류,엽경채류,22000111,6041404,536000,전라남도 해남군,...,100101,100101,봄배추,봄배추,12,kg,220001,1041401,대구북부도매시장,대구북부도매시장
9,2,정가수의,10,10,엽경채류,엽경채류,22000111,6041404,536000,전라남도 해남군,...,100101,100101,봄배추,봄배추,12,kg,220001,1041401,대구북부도매시장,대구북부도매시장

In [17]:
data.to_csv('원천정산경락가격품목목록조회.csv',encoding='cp949')

In [ ]:
import urllib.request 
import json 
import pandas as pd 

url = 'http://apis.data.go.kr/B552895/openapi/service/OrgPriceAuctionService/getRealMarketPriceList?ServiceKey=1yKMdSI9jST3NHMAjnb2FYpI4Gr+4FeldyFD8s1YlhoUHm3wywyvOp83ZtQLTh77IPD4F9O7WCcCfU0fkISOMg==&pageNo=1&numOfRows=10&delngDe=20151202&whsalCd=210005'
# 데이터 가져오기
response = urllib.request.urlopen(url) 
json_str = response.read().decode('utf-8')

# JSON으로 변환
json_object = json.loads(json_str)
json_object

# 데이터프레임으로 변환
# data = pd.json_normalize(json_object['body']['items'])
# data = pd.json_normalize(json_object['response']['body']['items'])
# data = pd.json_normalize(json_object['kinderInfo'])
# data = pd.json_normalize(json_object['data'])

# # 확인
# print(data.shape)
# data.head()

In [3]:
# xml 데이터 불러오기
# !pip install xml_to_dict
import requests
import pandas as pd
from xml_to_dict import XMLtoDict

url = 'http://apis.data.go.kr/B551182/codeInfoService/getAddrCodeList?pageNo=1&numOfRows=10&addrTp=1&ServiceKey=7y%2F8zMCQc8qOr3DIdtIzTDdbSB%2B01j5YgpvXZwtbeqQKIaylNhEaTcN95SYXagWmzcXBDMWwwLHRfhEiJSq%2FRw%3D%3D'
params ={}

# 데이터 가져오기
response = requests.get(url, params=params)

# 딕셔너리로 변환
xd = XMLtoDict()
xd.parse(response.content)

# 데이터프레임으로 변환
data = pd.DataFrame(xd.parse(response.content)['response']['body']['items']['item'])

data

{'OpenAPI_ServiceResponse': {'cmmMsgHeader': {'errMsg': 'SERVICE ERROR',
   'returnAuthMsg': 'SERVICE_KEY_IS_NOT_REGISTERED_ERROR',
   'returnReasonCode': '30'}}}